openapi: 3.0.1
info:
  title: Banking System API
  description: API for managing bank accounts.
  contact:
    name: Jesus Fernandez
    url: https://google.com
    email: jesus.fernandez.malpartida@gmail.com
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: v1.0
externalDocs:
  description: Springdoc OpenAPI Documentation
  url: https://springdoc.org/
servers:
  - url: http://localhost:9011
    description: Generated server url
tags:
  - name: Bank Account Controller
    description: Manage bank accounts
paths:
  /accounts/{account_id}:
    get:
      tags:
        - Bank Account Controller
      summary: Retrieve a bank account by ID
      description: Fetches a bank account using its unique ID.
      operationId: findById
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account found
          content:
            application/json: {}
        '404':
          description: Account not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BankAccount'
    put:
      tags:
        - Bank Account Controller
      summary: Update an existing bank account
      description: Updates the details of an existing bank account.
      operationId: update
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
        required: true
      responses:
        '200':
          description: Account updated
          content:
            application/json: {}
        '404':
          description: Account not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BankAccount'
    delete:
      tags:
        - Bank Account Controller
      summary: Delete a bank account
      description: Deletes a bank account using its ID.
      operationId: delete
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted
        '404':
          description: Account not found
  /accounts:
    get:
      tags:
        - Bank Account Controller
      summary: Retrieve all bank accounts
      description: Fetches a list of all bank accounts.
      operationId: findAll
      responses:
        '200':
          description: Accounts found
          content:
            application/json: {}
        '204':
          description: No accounts found
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccount'
    post:
      tags:
        - Bank Account Controller
      summary: Create a new bank account
      description: Adds a new bank account.
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankAccount'
        required: true
      responses:
        '201':
          description: Account created
          content:
            application/json: {}
        '401':
          description: Unauthorized action
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BankAccount'
  /accounts/{from_account_id}/{to_account_id}/transfer:
    post:
      tags:
        - Bank Account Controller
      summary: Transfer between accounts
      description: Transfers an amount from one account to another.
      operationId: transfer
      parameters:
        - name: from_account_id
          in: path
          required: true
          schema:
            type: string
        - name: to_account_id
          in: path
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Transfer successful
          content:
            application/json: {}
        '404':
          description: Account not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TransferResponse'
  /accounts/{account_id}/withdraw:
    post:
      tags:
        - Bank Account Controller
      summary: Withdraw from a bank account
      description: Withdraws an amount from the specified account.
      operationId: withdraw
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Withdrawal successful
          content:
            application/json: {}
        '404':
          description: Account not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BankAccount'
  /accounts/{account_id}/deposit:
    post:
      tags:
        - Bank Account Controller
      summary: Deposit into a bank account
      description: Deposits an amount into the specified account.
      operationId: deposit
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
        - name: amount
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Deposit successful
          content:
            application/json: {}
        '404':
          description: Account not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BankAccount'
components:
  schemas:
    BankAccount:
      required:
        - accountType
        - customerId
      type: object
      properties:
        id:
          type: string
        accountType:
          pattern: ^(saving|checking|fixed|vip|pyme)$
          type: string
        customerId:
          type: string
        balance:
          minimum: 0
          type: number
        maxMonthlyTrans:
          minimum: 0
          type: integer
          format: int32
        maintenanceFee:
          type: number
        allowedWithdrawalDay:
          type: string
          format: date
        withdrawAmountMax:
          type: number
        lstSigners:
          type: array
          items:
            type: string
        lstHolders:
          type: array
          items:
            type: string
        creationDate:
          type: string
          format: date-time
    TransferResponse:
      type: object
      properties:
        fromAccount:
          type: string
        toAccount:
          type: string
        amount:
          type: number
